AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Policy to read cloudformation stacks
Resources:
  pParameterSeceret:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: IAM Policy to read cloudformation stacks
      Path: /
      ManagedPolicyName: "${Stack::Name}-cloudformation-read-policy"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: CloudFormationRead
          Effect: Allow
          Action: 
            - cloudformation:DescribeStackEvents
            - cloudformation:DescribeStackSet
            - cloudformation:DescribeStackResource
            - cloudformation:DescribeChangeSet
            - cloudformation:ListChangeSets
            - cloudformation:DescribeStacks
          Resource: 
            - arn:aws:cloudformation:us-east-1:280062391276:stack/development*/*
            - arn:aws:cloudformation:us-east-1:280062391276:stackset/development*:*
        - Sid: CloudformationListStacks
          Effect: Allow
          Action: 
            - cloudformation:ListStacks
          Resource: *
        - Sid: CloudWatchDescribeLogsStream
          Effect: Allow
          Action: 
            - logs:DescribeLogStreams
            - logs:FilterLogEvents
            - logs:DescribeLogGroups
          Resource: arn:aws:logs:us-east-1:280062391276:log-group:development*