AWSTemplateFormatVersion: "2010-09-09"
Description: IAM role for CodeBuild to create AWS resources
Resources:
  RootRole:
    Type: 'AWS::IAM::Role'
    Description: IAM role for CodeBuild to create AWS resources
    Properties:
      RoleName: !Sub "${AWS::StackName}CodeBuildRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      MaxSessionDuration: 43200
Outputs: 
  CloudFormationEc2RoleArn:
    Description: CodebuildRoleArn
    Value: !GetAtt [RootRole, Arn]
    Export:
      Name: !Sub "${AWS::StackName}CodeBuildRole"